sudo: required
services: 
  - docker

before_install:
  - docker build -t otherstuff/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true otherstuff/docker-react npm run test -- --coverage
